// This file is automatically generated. Do not modify it directly.

/** @brief MAVLink message definitions for ardupilotmega */
#ifndef MAVLINK_ARDUPILOTMEGA_H
#define MAVLINK_ARDUPILOTMEGA_H

/** @brief  */
#ifndef HAVE_ENUM_HEADING_TYPE
#define HAVE_ENUM_HEADING_TYPE
typedef enum HEADING_TYPE
{
	HEADING_TYPE_NORTH=0, /*  | */
	HEADING_TYPE_EAST=1, /*  | */
	HEADING_TYPE_ENUM_END=2, /*  | */
} HEADING_TYPE;
#endif

/** @brief  */
#ifndef HAVE_ENUM_SPEED_TYPE
#define HAVE_ENUM_SPEED_TYPE
typedef enum SPEED_TYPE
{
	SPEED_TYPE_AIRSPEED=0, /*  | */
	SPEED_TYPE_GROUNDSPEED=1, /*  | */
	SPEED_TYPE_ENUM_END=2, /*  | */
} SPEED_TYPE;
#endif

/** @brief Commands to be executed by the MAV. They can be executed on user request, or as part of a mission script. If the action is used in a mission, the parameter mapping to the waypoint/mission message is as follows: Param 1, Param 2, Param 3, Param 4, X: Param 5, Y:Param 6, Z:Param 7. This command list is similar what ARINC 424 is for commercial aircraft: A data format how to interpret waypoint/mission data. NaN and INT32_MAX may be used in float/integer params (respectively) to indicate optional/default values (e.g. to use the component's current yaw or latitude rather than a specific value). See https://mavlink.io/en/guide/xml_schema.html#MAV_CMD for information about the structure of the MAV_CMD entries */
#ifndef HAVE_ENUM_MAV_CMD
#define HAVE_ENUM_MAV_CMD
typedef enum MAV_CMD
{
	MAV_CMD_NAV_WAYPOINT=16, /* Navigate to waypoint. |Hold time. (ignored by fixed wing, time to stay at waypoint for rotary wing)| Acceptance radius (if the sphere with this radius is hit, the waypoint counts as reached)| 0 to pass through the WP, if > 0 radius to pass by WP. Positive value for clockwise orbit, negative value for counter-clockwise orbit. Allows trajectory control.| Desired yaw angle at waypoint (rotary wing). NaN to use the current system yaw heading mode (e.g. yaw towards next waypoint, yaw to home, etc.).| Latitude| Longitude| Altitude|  */
	// ... [full content as above] ...
#endif // MAVLINK_ARDUPILOTMEGA_H

// Additional MAVLink message definitions can be added here.

// Copy the correct ardupilotmega.h from PayloadSdk/libs/gSDK/src/mavlink/include/mavlink/v2.0/ardupilotmega/ here for your build.
